serial:
  autoconnect: true
  baudrate: 115200
  port: /tmp/printer
  timeout: {}
plugins:
  pluginmanager:
    pip: /usr/bin/pip
    pip_force_user: true
  softwareupdate:
    pip_command: /usr/bin/pip
    _config_version: 6
    checks:
      octoprint:
        checkout_folder: null
        prerelease: false
        prerelease_channel: null
    notify_users: false
server:
  reverseProxy:
    prefixHeader: X-Script-Name
  onlineCheck:
    enabled: false
  pluginBlacklist:
    enabled: true
  commands:
    serverRestartCommand: sv restart octoprint
    systemRestartCommand: shutdown -r now
    systemShutdownCommand: shutdown -h now
system:
  actions: []
