#!/bin/sh
DAEMON=/usr/bin/octoprint
LOGDIR=/var/log/octoprint
BASEDIR=/var/lib/octoprint
CONFIGFILE=/etc/octoprint/config.yaml
PORT=5000

mkdir -p $LOGDIR
mkdir -p $BASEDIR

OPTIONS="serve --basedir $BASEDIR --config $CONFIGFILE --port $PORT \
         --logging $LOGDIR --iknowwhatimdoing --host 127.0.0.1"

if [ ! -x $DAEMON ]; then
    echo "$0: $DAEMON not found"
    sleep 10
    exit 1
fi

exec 2>&1
exec $DAEMON $OPTIONS

